apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-runpod
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-runpod
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - runpod.crossplane.io
    resources:
      - providerconfigs
      - providerconfigs/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - runpod.crossplane.io
    resources:
      - pods
      - pods/status
      - pods/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-runpod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-runpod
subjects:
  - kind: ServiceAccount
    name: provider-runpod
    namespace: crossplane-system
