apiVersion: runpod.crossplane.io/v1alpha1
kind: Template
metadata:
  name: vllm-base
  namespace: default
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
  forProvider:
    imageName: runpod/worker-v1-vllm:v2.25.2
    isServerless: true
    env:
      - name: MODEL_NAME
        value: "Qwen/Qwen2.5-Coder-7B-Instruct"
    containerDiskInGb: 30
