//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Endpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointList) DeepCopyInto(out *EndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Endpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointList.
func (in *EndpointList) DeepCopy() *EndpointList {
	if in == nil {
		return nil
	}
	out := new(EndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointObservation) DeepCopyInto(out *EndpointObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointObservation.
func (in *EndpointObservation) DeepCopy() *EndpointObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointParameters) DeepCopyInto(out *EndpointParameters) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	if in.ContainerDiskInGb != nil {
		in, out := &in.ContainerDiskInGb, &out.ContainerDiskInGb
		*out = new(int32)
		**out = **in
	}
	if in.GPUTypeIDs != nil {
		in, out := &in.GPUTypeIDs, &out.GPUTypeIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GPUCount != nil {
		in, out := &in.GPUCount, &out.GPUCount
		*out = new(int32)
		**out = **in
	}
	if in.WorkersMin != nil {
		in, out := &in.WorkersMin, &out.WorkersMin
		*out = new(int32)
		**out = **in
	}
	if in.WorkersMax != nil {
		in, out := &in.WorkersMax, &out.WorkersMax
		*out = new(int32)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(int32)
		**out = **in
	}
	if in.FlashBoot != nil {
		in, out := &in.FlashBoot, &out.FlashBoot
		*out = new(bool)
		**out = **in
	}
	if in.ScalerType != nil {
		in, out := &in.ScalerType, &out.ScalerType
		*out = new(ScalerType)
		**out = **in
	}
	if in.ScalerValue != nil {
		in, out := &in.ScalerValue, &out.ScalerValue
		*out = new(int32)
		**out = **in
	}
	if in.NetworkVolumeID != nil {
		in, out := &in.NetworkVolumeID, &out.NetworkVolumeID
		*out = new(string)
		**out = **in
	}
	if in.DataCenterIDs != nil {
		in, out := &in.DataCenterIDs, &out.DataCenterIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExecutionTimeoutMs != nil {
		in, out := &in.ExecutionTimeoutMs, &out.ExecutionTimeoutMs
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointParameters.
func (in *EndpointParameters) DeepCopy() *EndpointParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVolume) DeepCopyInto(out *NetworkVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVolume.
func (in *NetworkVolume) DeepCopy() *NetworkVolume {
	if in == nil {
		return nil
	}
	out := new(NetworkVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVolumeList) DeepCopyInto(out *NetworkVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVolumeList.
func (in *NetworkVolumeList) DeepCopy() *NetworkVolumeList {
	if in == nil {
		return nil
	}
	out := new(NetworkVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVolumeObservation) DeepCopyInto(out *NetworkVolumeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVolumeObservation.
func (in *NetworkVolumeObservation) DeepCopy() *NetworkVolumeObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkVolumeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVolumeParameters) DeepCopyInto(out *NetworkVolumeParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVolumeParameters.
func (in *NetworkVolumeParameters) DeepCopy() *NetworkVolumeParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkVolumeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVolumeSpec) DeepCopyInto(out *NetworkVolumeSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVolumeSpec.
func (in *NetworkVolumeSpec) DeepCopy() *NetworkVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkVolumeStatus) DeepCopyInto(out *NetworkVolumeStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkVolumeStatus.
func (in *NetworkVolumeStatus) DeepCopy() *NetworkVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pod) DeepCopyInto(out *Pod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pod.
func (in *Pod) DeepCopy() *Pod {
	if in == nil {
		return nil
	}
	out := new(Pod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodList) DeepCopyInto(out *PodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodList.
func (in *PodList) DeepCopy() *PodList {
	if in == nil {
		return nil
	}
	out := new(PodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodObservation) DeepCopyInto(out *PodObservation) {
	*out = *in
	if in.PortMappings != nil {
		in, out := &in.PortMappings, &out.PortMappings
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastStartedAt != nil {
		in, out := &in.LastStartedAt, &out.LastStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodObservation.
func (in *PodObservation) DeepCopy() *PodObservation {
	if in == nil {
		return nil
	}
	out := new(PodObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodParameters) DeepCopyInto(out *PodParameters) {
	*out = *in
	if in.ImageName != nil {
		in, out := &in.ImageName, &out.ImageName
		*out = new(string)
		**out = **in
	}
	if in.GPUTypeIDs != nil {
		in, out := &in.GPUTypeIDs, &out.GPUTypeIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GPUCount != nil {
		in, out := &in.GPUCount, &out.GPUCount
		*out = new(int32)
		**out = **in
	}
	if in.CloudType != nil {
		in, out := &in.CloudType, &out.CloudType
		*out = new(CloudType)
		**out = **in
	}
	if in.SupportPublicIP != nil {
		in, out := &in.SupportPublicIP, &out.SupportPublicIP
		*out = new(bool)
		**out = **in
	}
	if in.ContainerDiskInGb != nil {
		in, out := &in.ContainerDiskInGb, &out.ContainerDiskInGb
		*out = new(int32)
		**out = **in
	}
	if in.VolumeInGb != nil {
		in, out := &in.VolumeInGb, &out.VolumeInGb
		*out = new(int32)
		**out = **in
	}
	if in.VolumeMountPath != nil {
		in, out := &in.VolumeMountPath, &out.VolumeMountPath
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.DockerStartCmd != nil {
		in, out := &in.DockerStartCmd, &out.DockerStartCmd
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecreateOnTerminate != nil {
		in, out := &in.RecreateOnTerminate, &out.RecreateOnTerminate
		*out = new(bool)
		**out = **in
	}
	if in.DesiredState != nil {
		in, out := &in.DesiredState, &out.DesiredState
		*out = new(string)
		**out = **in
	}
	if in.DockerEntrypoint != nil {
		in, out := &in.DockerEntrypoint, &out.DockerEntrypoint
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.GlobalNetworking != nil {
		in, out := &in.GlobalNetworking, &out.GlobalNetworking
		*out = new(bool)
		**out = **in
	}
	if in.ContainerRegistryAuthID != nil {
		in, out := &in.ContainerRegistryAuthID, &out.ContainerRegistryAuthID
		*out = new(string)
		**out = **in
	}
	if in.Interruptible != nil {
		in, out := &in.Interruptible, &out.Interruptible
		*out = new(bool)
		**out = **in
	}
	if in.ComputeType != nil {
		in, out := &in.ComputeType, &out.ComputeType
		*out = new(string)
		**out = **in
	}
	if in.VCPUCount != nil {
		in, out := &in.VCPUCount, &out.VCPUCount
		*out = new(int32)
		**out = **in
	}
	if in.CPUFlavorIDs != nil {
		in, out := &in.CPUFlavorIDs, &out.CPUFlavorIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CPUFlavorPriority != nil {
		in, out := &in.CPUFlavorPriority, &out.CPUFlavorPriority
		*out = new(string)
		**out = **in
	}
	if in.DataCenterIDs != nil {
		in, out := &in.DataCenterIDs, &out.DataCenterIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataCenterPriority != nil {
		in, out := &in.DataCenterPriority, &out.DataCenterPriority
		*out = new(string)
		**out = **in
	}
	if in.GPUTypePriority != nil {
		in, out := &in.GPUTypePriority, &out.GPUTypePriority
		*out = new(string)
		**out = **in
	}
	if in.CountryCodes != nil {
		in, out := &in.CountryCodes, &out.CountryCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedCudaVersions != nil {
		in, out := &in.AllowedCudaVersions, &out.AllowedCudaVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinRAMPerGPU != nil {
		in, out := &in.MinRAMPerGPU, &out.MinRAMPerGPU
		*out = new(int32)
		**out = **in
	}
	if in.MinVCPUPerGPU != nil {
		in, out := &in.MinVCPUPerGPU, &out.MinVCPUPerGPU
		*out = new(int32)
		**out = **in
	}
	if in.MinDiskBandwidthMBps != nil {
		in, out := &in.MinDiskBandwidthMBps, &out.MinDiskBandwidthMBps
		*out = new(int32)
		**out = **in
	}
	if in.MinDownloadMbps != nil {
		in, out := &in.MinDownloadMbps, &out.MinDownloadMbps
		*out = new(int32)
		**out = **in
	}
	if in.MinUploadMbps != nil {
		in, out := &in.MinUploadMbps, &out.MinUploadMbps
		*out = new(int32)
		**out = **in
	}
	if in.TemplateID != nil {
		in, out := &in.TemplateID, &out.TemplateID
		*out = new(string)
		**out = **in
	}
	if in.NetworkVolumeID != nil {
		in, out := &in.NetworkVolumeID, &out.NetworkVolumeID
		*out = new(string)
		**out = **in
	}
	if in.VolumeEncrypted != nil {
		in, out := &in.VolumeEncrypted, &out.VolumeEncrypted
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodParameters.
func (in *PodParameters) DeepCopy() *PodParameters {
	if in == nil {
		return nil
	}
	out := new(PodParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpec) DeepCopyInto(out *PodSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpec.
func (in *PodSpec) DeepCopy() *PodSpec {
	if in == nil {
		return nil
	}
	out := new(PodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodStatus) DeepCopyInto(out *PodStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodStatus.
func (in *PodStatus) DeepCopy() *PodStatus {
	if in == nil {
		return nil
	}
	out := new(PodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}
